### ISSUE TITLE
Remove specific instance(s) from join-lemmy

### ISSUE THREAD

**Issue by jason-watkins** [LemmyNet/joinlemmy-site#186]
Beehaw.org has [chosen to defederate two of the largest Lemmy instances](https://beehaw.org/post/567170). While I can understand their points and support their ability to make whatever decision they choose, I think it will be confusing and unexpected for them to be the top instance in the popular section when a massive chunk of the overall community is not accessible from their platform.

@dessalines  and @Nutomic, would you be open to adding functionality to remove specific instances from the join-lemmy list?

**Comment by Nutomic** [comment]
Some instances are excluded from the list because they have questionnable content. But the fact that an instance blocks other instances is hardly a reason to remove it from the list. That is up to the admins and the users, if anyone doesnt like it they can signup somewhere else. By the same logic someone might argue that half the instances on the list should be removed because they block lemmygrad.

A better solution would be to show on the instance list how many federated users are visible from each instance. That number would be lower the more instances are being blocked.

**Comment by Falmarri** [comment]
>That is up to the admins and the users, if anyone doesnt like it they can signup somewhere else.

This is a bad take. The point is being an intro for people to learn about lemmy and just sign up and start interacting like they would on reddit. Having to know this arcane drama is going to kill a lot of people's interests.

Why not take it the other way? Their de-federation is up to the admins and users, and if they want to they can sign up there directly.
