### ISSUE TITLE
Excluded instances are back on the website

### ISSUE THREAD

**Issue by lionirdeadman** [LemmyNet/joinlemmy-site#226]
I don't know why but they are

**Comment by maxpoulin64** [comment]
It seems to be back up to date for me at the time of this comment. Recent news a back, instance list is filtered, users count it gone again.

**Comment by Nutomic** [comment]
I also noticed before that the active user counts were coming back sometimes. Its very weird because the site is rebuilt every hour using docker so there is no caching. And old docker images are regularly deleted. So I dont know why old versions of the site are coming back.

As a matter of fact there was a 5 week old docker image still on the server, maybe that was the cause. Although it didnt have any tag and couldnt be used.

**Comment by ruffsl** [comment]
> Although I dont see how, because it had `<none>` as tag.

If the tag for a built image is not specified, it is implicitly `latest`, and runs by default when no tag is included with the specified image name to use.

> If the tag is not specified, the command uses latest by default.
> https://docs.docker.com/engine/reference/commandline/tag/

**Comment by Nutomic** [comment]
The docker-compose.yml explicity sets `image: dessalines/joinlemmy-site:latest` so I dont see how it could end up running an image with tag `<none>`.

**Comment by lionirdeadman** [comment]
And... it's back again... how...?

**Comment by Nutomic** [comment]
Its back to the 6 week old docker image. Somehow after changing the image to `dessalines/joinlemmy-site:latest`, it is pulling the "latest` image from docker hub when running `docker-compose up -d`. That one hasnt been updated in a long time. Im changing it to use `docker-compose up -d` instead of a separate build step which should fix the problem.

**Comment by lionirdeadman** [comment]
Seems to not have happened in a bit, closing until it does again
