### ISSUE TITLE
Auto-generate instance data

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/joinlemmy-site#29]
I wrote a [basic crawler](https://yerbamate.ml/LemmyNet/lemmy-stats-crawler) which collects stats and metadata from Lemmy instances. We could use that to generate the list of instances automatically, based on certain criteria, such as:

- Instances which federate with a set of trusted instances (or at most x hops away)
- Min/max number of users
- Open registrations

Here's what we need to do to make this work:

- [x] Make instance description and other data machine readable ([here's how Peertube does it](https://peertube.social/nodeinfo/2.0.json)
- [x] Parse it in the crawler, and return it in a useful format (json, csv or whatever)
- [x] Generate the HTML with that data

**Comment by dessalines** [comment]
Nice! One thing I'd like, just so that it could be use elsewhere, is to create a git repo, maybe called `lemmy-instances`, that contains `instances.json` (which this crawler can write to). Then that json can be used by both joinlemmy, and probably lemmy-ui. 

Then we could set a cron-job for it to periodically re-run, and do commits on that repo.
