### ISSUE TITLE
Create a news/blog section

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/joinlemmy-site#80]
It would have multiple advantages to publish announcements and news about the project via join-lemmy.org:
- .org tld is better than .ml, less likely to be blocked
- makes it clearer that lemmy the software is not identical with the lemmy.ml instance
- could look more "professional"

The implementation could be relatively easy in this way: We make a Lemmy community specifically for project announcements (or reuse lemmy.ml/c/lemmy), and fetch the post listing via API from join-lemmy.org to display. Individual posts are also rendered on join-lemmy.org, with a comments link that goes to lemmy.ml. This has the advantage that posts still federate and can be commented on. It will required a community setting to let only mods create posts.

Instead of using the post listing, we could hardcode a list of announcements which are fetched. This would be useful in order to populate the blog section with all of our past announcements. Disadvantage is that every new post would require editing that list manually.

**Comment by dessalines** [comment]
Hrm.... I do like the idea of having a `news / blog` thing in the top bar, but it'd be so easy just to have that be a link to https://lemmy.ml/c/announcements or something. But I'd also be fine with a thing that uses `lemmy-js-client` to fetch from the API to get recent announcement posts, and build out a pretty blog page.

> Instead of using the post listing, we could hardcode a list of announcements which are fetched. This would be useful in order to populate the blog section with all of our past announcements. Disadvantage is that every new post would require editing that list manually.

We could also just restrict !announcements to lemmy only things, and not lemmy + new community announcements like it is now. IE we remove all the new community posts, and /c/announcements becomes our blog. Eventually since we'll have multiple default communities, it won't be too big an issue to separate them.

Another possibility is to link to https://github.com/LemmyNet/lemmy/blob/main/RELEASES.md , that is essentially the same thing, contains all our changes and such.

**Comment by Nutomic** [comment]
The main point is that our announcements should be visible directly on the join-lemmy.org domain, because it looks more official and is less likely to be caught in spam filters (compared to .ml domain). It would also help to clarify that lemmy.ml is just one instance of many.

Another way to implement this would be to have blog posts as markdown files in the repo, which get compiled to html at build time.

**Comment by dessalines** [comment]
> Another way to implement this would be to have blog posts as markdown files in the repo, which get compiled to html at build time.

I like this the best. But I don't know that we really need a separate blog apart from `RELEASES.md`
